name: Publish

on: 
  push:
    tags:
      - 'v*'

jobs:
  publish-on-success:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Dockerfile
            image: ghcr.io/${{ github.repository }}/event-listener

    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set current date as env variable
        run: echo "BUILD_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Docker meta
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ matrix.image }}
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}

      - name: Set the build date project toml file
        uses: sandstromviktor/toml-editor@2.0.0
        with:
          file: "pyproject.toml"
          key: "tool.serve.build-date"
          value: ${{ env.BUILD_DATE }}

      - name: Set the git tag or branch name in the project toml file
        uses: sandstromviktor/toml-editor@2.0.0
        with:
          file: "pyproject.toml"
          key: "tool.serve.gitref"
          value: ${{ github.ref_name }}

      - name: Set the image tag in the project toml file
        uses: sandstromviktor/toml-editor@2.0.0
        with:
          file: "pyproject.toml"
          key: "tool.serve.imagetag"
          value: ${{ steps.meta.outputs.version }}

      - name: Log in
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: True
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ${{ matrix.dockerfile }}
